authenticator/urls.py
from django.urls import path
from . import views

app_name = "authenticator"

urlpatterns = [
    path('', views.signup, name="new_user"),
    path('login/', views.signin, name="existing_user"),
    path('authenticated/dashboard/', views.dashboard, name="my_dashboard"),
    path('logout/', views.signout, name="logout_user")
]

school_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from base import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', general_views.home, name="index"),
    path('register/', include('authenticator.urls', namespace="authenticator")),
    path('user/suggestion/', include('submissions.urls', namespace="submissions"))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

submissions/urls.py
from django.urls import path
from . import views

app_name = "submissions"

urlpatterns = [
    path('', views.user_suggestion, name="new_suggestion"),
    path('get-course/', views.get_department_id, name="getCourse")
]

submissions/models.py
from datetime import date

from django.db import models
from base.models import BaseModel
from django.utils.translation import gettext_lazy as _


class Department(BaseModel):
    department_name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    wiki = models.CharField(max_length=128)
    description = models.TextField(max_length=256, blank=True)
    is_visible = models.BooleanField(default=False)

    class Meta:
        db_table = "submissions_department"
        verbose_name = _('department')
        verbose_name_plural = _('departments')

    def __str__(self):
        return self.department_name


class Course(BaseModel):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course_name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    fees = models.IntegerField()
    duration = models.IntegerField()

    class Meta:
        db_table = "submissions_course"
        verbose_name = _('course')
        verbose_name_plural = _('courses')

    def __str__(self):
        return self.course_name


class MaterialsChoices(models.Model):
    materials = models.CharField(max_length=128)

    class Meta:
        db_table = "submissions_materialschoices"
        verbose_name = _('materialschoice')
        verbose_name_plural = _('materialschoices')

    def __str__(self):
        return self.materials


class Suggestion(BaseModel):
    MALE = "M"
    FEMALE = "F"
    OTHER = "O"

    GENDER_CHOICE = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
        (OTHER, 'Other')
    )

    PURPOSES_CHOICE = (
        ('request', 'REQUEST'),
        ('enquiry', 'ENQUIRY'),
        ('order', 'ORDER'),
        ('return', 'RETURN')
    )

    name = models.CharField(max_length=128)
    dob = models.DateField()
    age = models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICE, max_length=1)
    phone = models.CharField(max_length=13)
    email = models.EmailField()
    address = models.TextField(max_length=128)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    purpose = models.CharField(choices=PURPOSES_CHOICE, default='enquiry',  max_length=7)
    materials = models.ManyToManyField(MaterialsChoices)

    class Meta:
        db_table = "submissions_suggestion"
        verbose_name = _('suggestion')
        verbose_name_plural = _('suggestions')

    def __str__(self):
        return self.purpose

submissions/forms.py
from django import forms
from django.forms import TextInput, DateInput, NumberInput, EmailInput, Textarea, \
    CheckboxSelectMultiple, RadioSelect, Select
from .models import Suggestion, MaterialsChoices, Department, Course
from django.utils.translation import gettext_lazy as _


class SuggestionForm(forms.ModelForm):
    class Meta:
        model = Suggestion
        exclude = ['creator', 'updater', 'auto_id', 'is_deleted']
        fields = ['name', 'dob', 'age', 'gender', 'phone', 'email', 'address', 'department', 'course', 'purpose',
                  'materials']

        widgets = {
            'name': TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'dob': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'age': NumberInput(attrs={'class': 'form-control'}),
            'gender': RadioSelect(choices=Suggestion.GENDER_CHOICE, attrs={'class': 'radio inline'}),
            'phone': TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'email': EmailInput(attrs={'class': 'form-control', 'required': 'required'}),
            'address': Textarea(attrs={'class': 'form-control', 'cols': '10', 'rows': '5', 'required': 'required', },),
            'department': Select(choices=Department.objects.filter(is_deleted=False), attrs={'class': 'form-select'}),
            'course': Select(choices=Course.objects.all(), attrs={'class': 'form-select'}),
            'purpose': Select(choices=Suggestion.PURPOSES_CHOICE, attrs={'class': 'form-select'}),
            'materials': CheckboxSelectMultiple(
                                                attrs={'class': 'form-check-input me-2 div1'})
        }
        labels = {
            'name': "Name",
            'dob': "Date or Birth",
        }
        error_messages = {
            'name': {
                'required': _('This field is required'),
            },
            'dob': {
                'required': _('This field is required'),
            },
        }

        # Advanced way to set readonly property
    def __init__(self, *args, **kwargs):
        super(SuggestionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            # if field in ['continent', 'country_code', 'country', 'state_code', 'state', 'city',
            #              'district', 'location_type', 'village', 'county', 'pin_code', 'formatted',
            #              'road_info', 'neighbourhood', 'latitude', 'longitude']:
            #     self.fields[field].widget.attrs['readonly'] = 'readonly'

            self.fields['course'].queryset = Course.objects.none()
            if 'course' in self.data:
                try:
                    department_pk = self.data.get('department')
                    self.fields['course'].queryset = Course.objects.filter(department__id=department_pk).order_by('course_name')
                except (ValueError, TypeError):
                    pass

            self.fields['materials'] = forms.ModelMultipleChoiceField(
                widget=forms.CheckboxSelectMultiple,
                queryset=MaterialsChoices.objects.all(),
            )

            if field == 'age':
                self.fields[field].widget.attrs['readonly'] = 'readonly'

submissions/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.html import format_html
from django.utils.safestring import mark_safe

from base.functions import get_auto_id, generate_form_errors
from .forms import SuggestionForm
import json
from .models import Course, Suggestion


@login_required(login_url='authenticator:existing_user')
def user_suggestion(request):
    if request.method == "POST":
        form = SuggestionForm(request.POST)
        if form.is_valid():
            suggestion = form.save(commit=False)
            suggestion.auto_id = get_auto_id(Suggestion)
            suggestion.creator = request.user
            suggestion.updater = request.user
            suggestion.save()
            # If submit & logout at the same time
            # auth.logout(request)
            # keep backup for sweat-alert
            response_data = {
                "status": "true",
                "title": "New User",
                "message": "Order confirmed.",
                "footer": '<a href="">Why do I have this issue?</a>',
                "redirect": 'false',
                "redirect_url": reverse('authenticator:my_dashboard')
            }
            # docstring with format & attached link
            message = """
            Order confirmed.
            <br />
            Click <a href='{url}'>here</a> to return back to home page.
            """
            url = reverse('authenticator:my_dashboard')
            messages.info(request, mark_safe(message.format(url=url)))
            return redirect('submissions:new_suggestion')
        else:
            messages.info(request, form.errors)
            return redirect('submissions:new_suggestion')
        #     message = generate_form_errors(form, formset=False)
        #     response_data = {
        #         "status": "false",
        #         "stable": "true",
        #         "title": "Form validation error",
        #         "message": message[0].messages[0]
        #     }
        # return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        form = SuggestionForm()
    context = {
        'title': "user suggestions",
        'is_bootstrap': True,
        'form': form,
    }
    return render(request, 'submissions/submission-form.html', context)


@login_required(login_url='authenticator:existing_user')
def get_department_id(request):
    data = json.loads(request.body)
    department_pk = data["id"]
    courses = Course.objects.filter(department__id=department_pk)
    return JsonResponse(list(courses.values("id", "course_name")), safe=False)

templates/submissions/submission-form.html
{% extends 'base.html' %}
{% block content %}
    <section class="vh-100">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100" style="margin-top: 50px;">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px; margin-bottom: 50px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Order</p>
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <form class=" mx-1 mx-md-4" method="POST" action="{{ url }}">
                                        {% csrf_token %}

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.name.id_for_label }}"
                                                       class="form-label">{{ form.name.label }}</label>
                                                {{ form.name }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.dob.id_for_label }}"
                                                       class="form-label">{{ form.dob.label }}</label>
                                                {{ form.dob }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.age.id_for_label }}"
                                                       class="form-label">{{ form.age.label }}</label>
                                                {{ form.age }}
                                            </div>
                                        </div>

                                        {#                                        <div class="d-flex flex-row align-items-center mb-4">#}
                                        {#                                            <div class="form-outline flex-fill mb-0">#}
                                        {#                                                <label for="{{ form.gender.id_for_label }}"#}
                                        {#                                                       class="form-check-label">{{ form.gender.label }}</label>#}
                                        {#                                                {{ form.gender }}#}
                                        {#                                            </div>#}
                                        {#                                        </div>#}
                                        <div class="control-group">
                                            <label for="{{ form.gender.id_for_label }}"
                                                   class="control-label">{{ form.gender.label }}</label>
                                            <div class="controls">
                                                <label class="radio inline">
                                                    <input id="id_gender_1" type="radio" value="M" name="gender"/>
                                                    Male
                                                </label>
                                                <label class="radio inline">
                                                    <input id="id_gender_2" type="radio" value="F" name="gender"/>
                                                    Female
                                                </label>
                                                <label class="radio inline">
                                                    <input id="id_gender_3" type="radio" value="O" name="gender"/>
                                                    Other
                                                </label>
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.phone.id_for_label }}"
                                                       class="form-label">{{ form.phone.label }}</label>
                                                {{ form.phone }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.email.id_for_label }}"
                                                       class="form-label">{{ form.email.label }}</label>
                                                {{ form.email }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.address.id_for_label }}"
                                                       class="form-label">{{ form.address.label }}</label>
                                                {{ form.address }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.department.id_for_label }}"
                                                       class="form-label">{{ form.department.label }}</label>
                                                {{ form.department }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.course.id_for_label }}"
                                                       class="form-label">{{ form.course.label }}</label>
                                                {{ form.course }}
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-center mb-4">
                                            <div class="form-outline flex-fill mb-0">
                                                <label for="{{ form.purpose.id_for_label }}"
                                                       class="form-label">{{ form.purpose.label }}</label>
                                                {{ form.purpose }}
                                            </div>
                                        </div>

                                        <div class="control-group mb-5">
                                            <div class="controls">
                                                <label for="{{ form.materials.id_for_label }}"
                                                       class="form-check-label">{{ form.materials.label }}</label>
                                                {{ form.materials }}
                                            </div>
                                        </div>

                                        <div class="d-grid gap-2 d-md-flex justify-content-md-center">
                                            <button class="btn btn-primary me-md-2" type="submit">Submit</button>
                                            <button class="btn btn-primary" type="button"
                                                    onclick="location.href='{% url 'authenticator:logout_user' %}'">Sign-out</button>
                                        </div>

{#                                    for messages #}
                                        {% if messages %}
                                            {% for message in messages %}

                                                <div class="card" style="margin-top: 50px;">
                                                    <div class="card-body">
                                                        {{ message }}
                                                    </div>
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://mdbootstrap.com/img/Photos/new-templates/bootstrap-registration/draw1.png"
                                         class="img-fluid" alt="Sample image"/>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{#    for dependend dropdown list department --> courses #}
    <script type="text/javascript">
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        let csrf_token = '{{ csrf_token }}';


        let department_field = document.getElementById("id_department");
        department_field.addEventListener("change", getDepartmentId);

        function getDepartmentId(e) {
            let department = e.target.value;
            {#console.log(e.target.value);#}

            const data = {'id': department};
            let url = "{% url 'submissions:getCourse' %}";

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrf_token
                },
                body: JSON.stringify(data),
            })
                .then((response) => response.json())
                .then((data) => {
                    {#console.log('Success:', data);#}
                    let course_field = document.getElementById("id_course");
                    course_field.innerHTML = '<option value="" selected}>Select Course</option>'
                    for (let i = 0; i < data.length; i++) {
                        /* loop across the data gotten from the backend */
                        course_field.innerHTML += `<option value="${data[i]['id']}">${data[i]['course_name']}</option>`
                        // console.log(${data[i]['name']});
                    }
                })
                .catch((error) => {
                    console.error('Error:', error);
                    alert("Error");
                });
        }

        {#when select dob auto calculate age #}
        let date_of_birth = document.getElementById("id_dob");
        date_of_birth.addEventListener("change", ageCalc);

        function ageCalc() {
            let date_of_birth = document.getElementById("id_dob").value;
            var today = new Date();
            var birthDate = new Date(date_of_birth);
            var age = today.getFullYear() - birthDate.getFullYear();
            document.getElementById("id_age").value = age;
        }
    </script>
{% endblock %}