authenticator/urls.py
from django.urls import path
from . import views

app_name = "authenticator"

urlpatterns = [
    path('', views.signup, name="new_user"),
    path('login/', views.signin, name="existing_user"),
    path('authenticated/dashboard/', views.dashboard, name="my_dashboard"),
    path('logout/', views.signout, name="logout_user")
]

school_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from base import views as general_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', general_views.home, name="index"),
    path('register/', include('authenticator.urls', namespace="authenticator")),
    path('user/suggestion/', include('submissions.urls', namespace="submissions"))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

submissions/urls.py
from django.urls import path
from . import views

app_name = "submissions"

urlpatterns = [
    path('', views.user_suggestion, name="new_suggestion"),
    path('get-course/', views.get_department_id, name="getCourse")
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: #6f2cf4">
    <div class="container-fluid">
{#    check user authenticated or not and set appropriate link for home page#}
        {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'authenticator:my_dashboard' %}">{{ app_title }}</a>
        {% else %}
        <a class="navbar-brand" href="{% url 'index' %}">{{ app_title }}</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link active" aria-current="page" href="{% url 'authenticator:my_dashboard' %}">Home</a>
                    {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    {% endif %}
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Department
                    </a>
                    <ul class="dropdown-menu">
                        {% for department in departments %}
                        <li><a class="dropdown-item" href="{{ department.wiki }}">{{ department.department_name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>

            </ul>
{#        if user is authenticated show user name and also hide login, register links and show logout link only.#}
            {% if user.is_authenticated %}
            <ul class="d-flex navbar-nav">

                <li class="nav-item">
                    {% if user.is_superuser %}
                    <a class="nav-link active" aria-current="page" href="/admin">Hi, {{user.username}}</a>
                    {% else %}
                    <a class="nav-link active" aria-current="page" href="{% url 'authenticator:my_dashboard' %}">Hi, {{user.username}}</a>
                    {% endif %}
                </li>

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authenticator:logout_user' %}">Logout</a>
                </li>
            </ul>
            {% else %}
            <ul class="d-flex navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authenticator:new_user' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'authenticator:existing_user' %}">Login</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>